name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security scan daily at 3 AM UTC
    - cron: '0 3 * * *'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run npm audit
      run: npm audit --audit-level high
      continue-on-error: true
      
    - name: Run secret scanning
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
      continue-on-error: true
      
    - name: Check for API keys and sensitive data
      run: |
        echo "Checking for sensitive data patterns..."
        if grep -r "api[_-]key" . --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=dist; then
          echo "::warning::Potential API key references found"
        fi
        if grep -r "secret" . --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=dist --exclude="*.yml"; then
          echo "::warning::Potential secret references found"
        fi
        
    - name: CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: javascript-typescript
        
    - name: Build for CodeQL
      run: npm run build
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3